### ISSUE TITLE
SECURITY ISSUE

### ISSUE THREAD

**Issue by dtkdtk** [euberdeveloper/esm-module-alias#9]
Hello! You had leaked `.env` file with `GITHUB_TOKEN`.
![image](https://github.com/user-attachments/assets/faceda76-570b-4902-b8e9-0fc967e00faa)
![image](https://github.com/user-attachments/assets/864ab697-6d96-4714-b0d0-cc39728641cd)

Please add `.npmignore` (similar to `.gitignore`) to fix this issue.

**Comment by dtkdtk** [comment]
@euberdeveloper

**Comment by dtkdtk** [comment]
https://github.com/euberdeveloper/esm-module-alias/pull/10
Please merge the PR

And reset your token

**Comment by euberdeveloper** [comment]
Thanks a lot for your issue, I really got scared, luckily the token seems to be expired since a long time. But thanks a lot
